# Render.com Configuration File
# Este arquivo configura o deploy para produção

# Build Settings
build:
  command: "npm ci --only=production && npm run build"
  publishDir: "dist/spa"

# Runtime Settings  
start:
  command: "npm start"

# Environment
env:
  NODE_ENV: "production"
  
# Health Check
healthCheck:
  path: "/health.json"
  
# Redirects for SPA
redirects:
  - from: "/*"
    to: "/index.html"
    status: 200